name: pr
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: install dependencies
      run: npm install --include=dev
    - name: build
      run: npm run build
